/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.4.0.0                                               */
/*  Date (dd.mm.yyyy): 28.12.2024   Time (hh:mm): 15:29                        */
/*******************************************************************************/


#ifndef _MKR_RGB_SHIELD_DISPLAY_120_28_RESOURCES_H_
#define _MKR_RGB_SHIELD_DISPLAY_120_28_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY_120_28 0
#define DISPLAY_120_28_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define DISPLAY_120_28_X_RESOLUTION 120
#define DISPLAY_120_28_Y_RESOLUTION 28
#define DISPLAY_120_28_THEME_1 0
#define DISPLAY_120_28_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_120_28_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_BLACK 29
#define GX_COLOR_ID_BLUE 30
#define GX_COLOR_ID_GREEN 31
#define GX_COLOR_ID_RED 32
#define GX_COLOR_ID_CIAN 33
#define GX_COLOR_ID_DARK_DARK_BLUE 34
#define GX_COLOR_ID_YELLOW 35
#define GX_COLOR_ID_WHITE 36
#define GX_COLOR_ID_GRAY 37
#define GX_COLOR_ID_DARK_YELLOW 38
#define GX_COLOR_ID_TEMPERATURE 39
#define GX_COLOR_ID_DARK_DARK_RED 40
#define GX_COLOR_ID_DARK_DARK_GREEN 41
#define GX_COLOR_ID_CUSTOM_COLOR 42
#define DISPLAY_120_28_COLOR_TABLE_SIZE 43

/* Font ID definitions                                                         */

#define GX_FONT_ID_FONT_5X7 4
#define GX_FONT_ID_MONOGRAM 5
#define GX_FONT_ID_NORMAL_3X7 6
#define GX_FONT_ID_MYFONT3X5 7
#define GX_FONT_ID_MYFONT3X5_2 8
#define DISPLAY_120_28_FONT_TABLE_SIZE 9

/* Pixelmap ID definitions                                                     */

#define DISPLAY_120_28_PIXELMAP_TABLE_SIZE 5

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_3 1
#define GX_STRING_ID_STRING_1 2
#define GX_STRING_ID_STRING_2 3
#define GX_STRING_ID_STRING_4 4
#define GX_STRING_ID_STRING_5 5
#define GX_STRING_ID_STRING_6 6
#define GX_STRING_ID_STRING_7 7
#define GX_STRING_ID_STRING_8 8
#define GX_STRING_ID_STRING_9 9
#define GX_STRING_ID_STRING_10 10
#define GX_STRING_ID_STRING_11 11
#define GX_STRING_ID_STRING_12 12
#define GX_STRING_ID_STRING_13 13
#define DISPLAY_120_28_STRING_TABLE_SIZE 14

#endif                                       /* sentry                         */
